// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/clientes": {
            "get": {
                "description": "Retorna uma lista de todos os clientes cadastrados com seus endereços.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clientes"
                ],
                "summary": "Lista todos os clientes",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/ecommerce_clientes_internal_domain.Cliente"
                            }
                        }
                    },
                    "500": {
                        "description": "Erro interno ao listar clientes",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Cria um novo cliente com seus dados e endereços.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clientes"
                ],
                "summary": "Cria um novo cliente",
                "parameters": [
                    {
                        "description": "Dados para criação do cliente",
                        "name": "cliente",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ecommerce_clientes_internal_application.ClienteInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/ecommerce_clientes_internal_domain.Cliente"
                        }
                    },
                    "400": {
                        "description": "Corpo da requisição inválido",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Erro interno ao criar cliente",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "ecommerce_clientes_internal_application.ClienteInput": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "enderecos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ecommerce_clientes_internal_application.EnderecoInput"
                    }
                },
                "nome": {
                    "type": "string"
                }
            }
        },
        "ecommerce_clientes_internal_application.EnderecoInput": {
            "type": "object",
            "properties": {
                "cep": {
                    "type": "string"
                },
                "cidade": {
                    "type": "string"
                },
                "estado": {
                    "type": "string"
                },
                "rua": {
                    "type": "string"
                }
            }
        },
        "ecommerce_clientes_internal_domain.Cliente": {
            "type": "object",
            "properties": {
                "alteradoEm": {
                    "type": "string"
                },
                "criadoEm": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "enderecos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ecommerce_clientes_internal_domain.Endereco"
                    }
                },
                "id": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                }
            }
        },
        "ecommerce_clientes_internal_domain.Endereco": {
            "type": "object",
            "properties": {
                "cep": {
                    "type": "string"
                },
                "cidade": {
                    "type": "string"
                },
                "estado": {
                    "type": "string"
                },
                "id": {
                    "type": "integer",
                    "format": "int64"
                },
                "rua": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/clientes",
	Schemes:          []string{},
	Title:            "API de Clientes do E-commerce",
	Description:      "Microsserviço responsável pelo gerenciamento de clientes.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
