basePath: /clientes
definitions:
  ecommerce_clientes_internal_application.ClienteInput:
    properties:
      email:
        type: string
      enderecos:
        items:
          $ref: '#/definitions/ecommerce_clientes_internal_application.EnderecoInput'
        type: array
      nome:
        type: string
    type: object
  ecommerce_clientes_internal_application.EnderecoInput:
    properties:
      cep:
        type: string
      cidade:
        type: string
      estado:
        type: string
      rua:
        type: string
    type: object
  ecommerce_clientes_internal_domain.Cliente:
    properties:
      alteradoEm:
        type: string
      criadoEm:
        type: string
      email:
        type: string
      enderecos:
        items:
          $ref: '#/definitions/ecommerce_clientes_internal_domain.Endereco'
        type: array
      id:
        type: string
      nome:
        type: string
    type: object
  ecommerce_clientes_internal_domain.Endereco:
    properties:
      cep:
        type: string
      cidade:
        type: string
      estado:
        type: string
      id:
        format: int64
        type: integer
      rua:
        type: string
    type: object
info:
  contact: {}
  description: Microsserviço responsável pelo gerenciamento de clientes.
  title: API de Clientes do E-commerce
  version: "1.0"
paths:
  /clientes:
    get:
      description: Retorna uma lista de todos os clientes cadastrados com seus endereços.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/ecommerce_clientes_internal_domain.Cliente'
            type: array
        "500":
          description: Erro interno ao listar clientes
          schema:
            type: string
      summary: Lista todos os clientes
      tags:
      - clientes
    post:
      consumes:
      - application/json
      description: Cria um novo cliente com seus dados e endereços.
      parameters:
      - description: Dados para criação do cliente
        in: body
        name: cliente
        required: true
        schema:
          $ref: '#/definitions/ecommerce_clientes_internal_application.ClienteInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/ecommerce_clientes_internal_domain.Cliente'
        "400":
          description: Corpo da requisição inválido
          schema:
            type: string
        "500":
          description: Erro interno ao criar cliente
          schema:
            type: string
      summary: Cria um novo cliente
      tags:
      - clientes
swagger: "2.0"
